In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# train test split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# scaling

in neural netwrok, generally we should pass same scale inputs

In [8]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
x_train

array([[-0.72280527, -1.96055624, -0.7385282 , ..., -1.01214534,
         0.84329602, -0.53307743],
       [ 0.05476984,  0.57001903,  0.08789401, ...,  0.47680782,
         1.17667102,  0.97756506],
       [-0.54490985, -0.27887395, -0.54915708, ..., -0.86332634,
        -0.78874872, -0.36839172],
       ...,
       [-0.67402749, -0.59174507, -0.69741473, ..., -0.66825898,
        -1.93980467, -0.58387879],
       [-0.00261578,  1.81920301, -0.00554569, ..., -0.13220531,
        -1.04748752, -0.03790379],
       [-0.45596215, -0.4445116 , -0.45945497, ..., -0.12457357,
         0.25449939, -0.40635318]])

In [10]:
y_train

313    B
36     M
480    B
464    B
232    B
      ..
282    M
437    B
136    B
560    B
497    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,

# Numpy arrays to PyTorch tensors

using "from_numpy" function

In [13]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch. from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
x_train_tensor

tensor([[-0.7228, -1.9606, -0.7385,  ..., -1.0121,  0.8433, -0.5331],
        [ 0.0548,  0.5700,  0.0879,  ...,  0.4768,  1.1767,  0.9776],
        [-0.5449, -0.2789, -0.5492,  ..., -0.8633, -0.7887, -0.3684],
        ...,
        [-0.6740, -0.5917, -0.6974,  ..., -0.6683, -1.9398, -0.5839],
        [-0.0026,  1.8192, -0.0055,  ..., -0.1322, -1.0475, -0.0379],
        [-0.4560, -0.4445, -0.4595,  ..., -0.1246,  0.2545, -0.4064]],
       dtype=torch.float64)

In [15]:
x_train_tensor.shape

torch.Size([455, 30])

# Defining the model

while defining the structure of neural network model we use OOPs in pytorch

In [33]:
class MySimpleNN():

  # constructor
  def __init__(self, X):  #here X is my training set i.e x_train_tensor

     self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)  # weight will be assigned with random values & matrix size will be contains weights i.e no. of inputs we have (30,1)
     self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)                # bais is only one which is defined as zero in starting

  # forward pass
  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias   # z=wx+b
    y_pred = torch.sigmoid(z)                       # sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss



# Important Parameters

In [44]:
learning_rate = 0.1  # lr is used while gradients descent or any optimizers
epoch = 25            # no. of runs or iterations of our data

# Training Pipeline

In [46]:
# create model
model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range(epoch):

  # forward pass
  y_pred = model.forward(x_train_tensor)
  # print(y_pred)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients     (before going to next epoch , we must need to make our parameters zero in pytorch, otherwise in pytorch weights or gradients values gets accumulated )
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.379706472648156
Epoch: 2, Loss: 3.258472144817779
Epoch: 3, Loss: 3.13532058963266
Epoch: 4, Loss: 3.009552794557646
Epoch: 5, Loss: 2.8802130547394422
Epoch: 6, Loss: 2.7475822625377444
Epoch: 7, Loss: 2.6079051219120863
Epoch: 8, Loss: 2.462895999579839
Epoch: 9, Loss: 2.3169245491451225
Epoch: 10, Loss: 2.171025779817642
Epoch: 11, Loss: 2.029054910997367
Epoch: 12, Loss: 1.886405308891843
Epoch: 13, Loss: 1.7473785546836307
Epoch: 14, Loss: 1.6138168572692773
Epoch: 15, Loss: 1.485832772195298
Epoch: 16, Loss: 1.3648476953809747
Epoch: 17, Loss: 1.2562694216253147
Epoch: 18, Loss: 1.1609492937263395
Epoch: 19, Loss: 1.0794070510978244
Epoch: 20, Loss: 1.0115842940111388
Epoch: 21, Loss: 0.9566815496110442
Epoch: 22, Loss: 0.9131970680074547
Epoch: 23, Loss: 0.8791764358500805
Epoch: 24, Loss: 0.8525597794248414


In [47]:
model.weights # matrix of (30,1)

tensor([[-0.2295],
        [ 0.5614],
        [-0.1356],
        [ 0.0284],
        [-0.3688],
        [-0.0017],
        [-0.4131],
        [ 0.1100],
        [ 0.2622],
        [ 0.4860],
        [-0.3866],
        [ 0.6688],
        [ 0.2421],
        [ 0.4935],
        [ 0.3302],
        [ 0.0626],
        [-0.1160],
        [ 0.2981],
        [-0.1846],
        [-0.1623],
        [-0.3267],
        [-0.2010],
        [ 0.4387],
        [ 0.3877],
        [ 0.2299],
        [-0.0683],
        [-0.0898],
        [-0.0881],
        [ 0.2434],
        [-0.1862]], dtype=torch.float64, requires_grad=True)

In [48]:
model.bias  # bais is a scaler with single item  i.e 0

tensor([-0.1653], dtype=torch.float64, requires_grad=True)

# Evaluation

In [51]:
# model evaluation
with torch.no_grad():  # no_grad() beacuse during evaluation we are not calculating any gradients
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5180055499076843
