In [50]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"USing GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available, Using CPU.")

GPU is not available, Using CPU.


# Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)
a

tensor([[-2.3901e-27,  4.4676e-41, -2.3901e-27],
        [ 4.4676e-41,  0.0000e+00,  0.0000e+00]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.4063, 0.2955, 0.7195],
        [0.0037, 0.0016, 0.8751]])

In [8]:
#manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
#manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways

# arange
print("using arange ->",torch.arange(0,10,2))

#using linspace (linearly spaced)
print("using linspace ->", torch.linspace(0,10,10))

#using eye (eye stands for identity matrix)
print("using eye ->",torch.eye(5))

# using full
print("using full ->", torch.full((3,3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes


In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [18]:
# by using empty_like we can build same shape like tensor x
torch.empty_like(x)

tensor([[3616445622929465956, 6068371993578712373, 3977586878902318641],
        [6501281641681989678, 7309453675965983778, 8315168162784306286]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

here rand_like generates float values between 0 to 1 and x tensor in above error contains int tensor only , so we need to to convert the datatype first , so lets understand datatype of tensor in pytorch

In [29]:
# so to solve above error define explicitly data type
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [23]:
# find data type
# use dtype function just like numpy
x.dtype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
# using to()
# for converting tensor data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical operations

# 1. Scalar operation

(during sczler operation we have one tensor part and one scaler )

In [30]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [38]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

# 2. Element wise operation

(here for element wise operation we have 2 or more tensors)

In [40]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [47]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0060, 0.0377, 0.5277],
        [0.2472, 0.1394, 0.4235]])

There are some element wise operation that we can be perform on single tensor

In [51]:
 c = torch.tensor([1, -2, 3, -4])

In [52]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [53]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [54]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [55]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [56]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [57]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [58]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3. Reduction operation

(jaha hum ek poore tensor ko ek single number mai reduce krte ho)

In [65]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 9., 8.],
        [9., 7., 9.]])

In [67]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([22., 25.])

In [66]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 8.0000, 8.5000])

In [68]:
# median
torch.median(e)

tensor(8.)

In [69]:
# max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [70]:
# product
torch.prod(e)

tensor(204120.)

In [71]:
# standard deviation
torch.std(e)

tensor(1.6021)

In [72]:
# variance
torch.var(e)

tensor(2.5667)

In [73]:
# argmax (give max number item's position in tensor)
torch.argmax(e)

tensor(1)

In [74]:
# argmin (give min number item's position in tensor)
torch.argmin(e)

tensor(0)

# 4. Matrix operations

In [76]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[6, 1, 5],
        [5, 0, 4]])
tensor([[3, 8],
        [8, 3],
        [3, 5]])


In [77]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[41, 76],
        [27, 60]])

In [78]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [79]:
# transpose
torch.transpose(f, 0, 1)

tensor([[6, 5],
        [1, 0],
        [5, 4]])

In [80]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 6., 4.],
        [0., 8., 4.],
        [7., 2., 3.]])

In [81]:
# determinant
torch.det(h)

tensor(-56.0000)

In [82]:
# inverse
torch.inverse(h)

tensor([[-0.2857,  0.1786,  0.1429],
        [-0.5000,  0.5000,  0.0000],
        [ 1.0000, -0.7500,  0.0000]])

# 5. Comparison operations

In [83]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 5, 6],
        [2, 9, 5]])
tensor([[0, 4, 2],
        [7, 1, 1]])


In [84]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

# 6. Special functions

In [85]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [86]:
# log
torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [87]:
# exp
torch.exp(k)

tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])

In [88]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [89]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [90]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [91]:
# relu
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

# Inplace Operations

In [92]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [99]:
# isse ek problem hai addition of both tensor ke baad ek new tensor banega joki bhot space lega agr humara dataset bhoot bada ho joki tensors form m store ho , par ese addition operation karne se bhot jada memory lagegi due to another big dataset tensor gets created, thats why we inplace opertion i.e add_()
m + n

tensor([[1.7536, 0.2812, 2.2271],
        [1.2174, 1.6773, 2.1778]])

In [100]:
m.add_(n)

tensor([[1.7536, 0.2812, 2.2271],
        [1.2174, 1.6773, 2.1778]])

In [101]:
m

tensor([[1.7536, 0.2812, 2.2271],
        [1.2174, 1.6773, 2.1778]])

In [102]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [96]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [97]:
m.relu_()

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [103]:
m

tensor([[1.7536, 0.2812, 2.2271],
        [1.2174, 1.6773, 2.1778]])

By adding underscore infront of function or operation and it will make it a inplace operation

# Copying a Tensor

In [104]:
a = torch.rand(2,3)
a

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [105]:
b = a #assignment operator se copy banaya par iss approach m problem ye hai ki agr copy tensor m changes kiye toh original tensor mai bhi changes ho jayege

In [106]:
b

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [107]:
a[0][0] = 0

In [108]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [109]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [110]:
id(a)

136930137908496

In [111]:
id(b)

136930137908496

To copy tensors use clone function instead of assignment operator because this time by using clone function , we are assigning different memory to both tensors (jisse ek pe operation lagane pe dusre pe farak nhi padeta h)

In [112]:
b = a.clone()

In [113]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [114]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [115]:
a[0][0] = 10

In [116]:
a

tensor([[10.0000,  0.0887,  0.4890],
        [ 0.5887,  0.7340,  0.8497]])

In [117]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [118]:
id(a)

136930137908496

In [119]:
id(b)

136930137907728

now lets see how to perform tensor operations on GPU


# Tensor Operations on GPU

In [2]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [4]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.4407, 0.6617, 0.3784],
        [0.0499, 0.9231, 0.1475]], device='cuda:0')

In [5]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.1639, 0.5163, 0.7661],
        [0.0742, 0.7424, 0.6122]])

ye jo naya tensor hai voh cpu ke upar bana hai , kuki hume device='cuda:0' print nhi hua hai, toh ab hum iss cpu wale tensor ko gpu pe leke ate h dekiye

In [9]:
b = a.to(device)

In [10]:
b + 5

tensor([[5.1639, 5.5163, 5.7661],
        [5.0742, 5.7424, 5.6122]], device='cuda:0')

In [12]:
import torch
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_time = time.time()
time_cpu = end_time - start_time

print(f"Time taken on CPU: {time_cpu:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")

# Measur time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
end_time = time.time()
time_gpu = end_time - start_time

print(f"Time taken on GPU: {time_gpu:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", time_cpu / time_gpu)

Time taken on CPU: 18.7470 seconds
Time taken on GPU: 0.5634 seconds

Speedup (CPU time / GPU time): 33.27357760010562


mtlb 30 times faster is gpu , jo kam cpu ke sath apko 30hr m hoga jo gpu se 1hr m hoga , isly nivida ke stocks itne baad rhe h :)

# Reshaping Tensors

In [3]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
# reshape
a.reshape(2,2,2,2)

#in reshape dayan rkna jab bhi ap reshape karte hai toh original shape of tensor and new reshaped tensor shape product should be same

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [7]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
b = torch.rand(2,3,4)
b

tensor([[[0.2332, 0.6712, 0.6651, 0.2841],
         [0.6110, 0.1895, 0.3820, 0.4019],
         [0.6657, 0.2277, 0.0074, 0.0818]],

        [[0.6223, 0.2827, 0.6096, 0.5638],
         [0.5344, 0.6978, 0.8842, 0.7310],
         [0.8314, 0.6637, 0.3056, 0.7812]]])

In [9]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [11]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

unsqueeze can be useful when we are training a deep learning model for example image classification model it will take input in n batches (n,226,226,3) instead of one single image(226,226,3), so to make a single image in batches we can use unsqueeze which will make our dimension like this
torch.Size([1, 226, 226, 3])

In [13]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

# (just opposite of squeeze, it will reduce the dimensions)

torch.Size([20])

# NumPy and PyTorch

here we'll see how can we move tensors between numpy and pytorch
(hum easily numpy array ko pytorch tensor mai convert kar skte hai and vice versa)

In [14]:
import numpy as np

In [15]:
# Converting pytorch tensors into numpy array
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [17]:
b = a.numpy()
b

array([1, 2, 3])

In [18]:
type(b)

numpy.ndarray

In [19]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [20]:
torch.from_numpy(c)

tensor([1, 2, 3])